### ISSUE TITLE
Build fails with xa v2.4.1

### ISSUE THREAD

**Issue by lifepillar** [cmosher01/Epple-II#18]
Apparently, there are some deprecations in [xa v2.4.x](https://www.floodgap.com/retrotech/xa/). In particular, `-M` should be replaced by `-XMASM`, and `-XXA23` is required to allow some older and deprecated features. An Epple-II build fails with:

```
/opt/homebrew/opt/xa/bin/xa -C -M -R -c -bt 0  -o display2.o65  display2.s65
CANCEL   LDA   #("\"|%10000000) ;BACKSLASH AFTER CANCELLED LINE
keyin.s65:line 168: 0058:Syntax error
Break after 1 errors
```

Could the build flags of this repo and of [Apple-II-Source](https://github.com/cmosher01/Apple-II-Source) be updated so that those assembly files compile with the current xa?

**Comment by cmosher01** [comment]
Fixed in Apple-II-Source, with version 1.2.1:

https://github.com/cmosher01/Apple-II-Source/commit/8ab5049415370a4282b8c23b0c216817f3ad1e4f

NOTES:
Ubuntu 24 defaults to xa 2.4.x, while Ubuntu 22 defaults to xa 2.3.x. This update works fine in 2.4. However, 2.3 gives "Unknown option 'X' - ignoring!" error message, but still works fine.

I also added "make check" after the build to verify all generated binaries are correct.

**Comment by cmosher01** [comment]
Fixed in Epple-II (2.0 branch): https://github.com/cmosher01/Epple-II/commit/ab9c52577cc505dc0044b8e0c2db51ee6289315c

**Comment by lifepillar** [comment]
Thanks, it works! Branch 2.0 does not have the `rom` folder any longer: is there a new build step that replaces `cd rom && make`?

**Comment by cmosher01** [comment]
The `rom` directory has been moved to `share/Resources/rom`.

You can examine the complete build process in the Workflow definition: `.github/workflows/build.yaml`
